- name: (1) Importar o arquivo de execusão do Loki
  become: yes
  get_url:
    url: https://github.com/grafana/loki/releases/download/v2.8.2/loki-linux-amd64.zip
    dest: /usr/local/bin/
    validate_certs: no

- name: (2) Descompactar o arquivo loki
  become: yes
  unarchive:
    src: /usr/local/bin/loki-linux-amd64.zip
    dest: /usr/local/bin/
    remote_src: yes

- name: (2.1) Remover o arquivoo Zip do Loki
  file:
    path: /usr/local/bin/loki-linux-amd64.zip
    state: absent